"""Fitting corpus: strata, recipes, position mask, on-policy builder.

Corpus choice is load-bearing — fitting a Jacobian lens averages the network's input→output
Jacobian over the corpus's activation distribution, exactly like quantization-calibration data
(see docs/DESIGN.md). So the corpus is a first-class, swappable, provenance-stamped config:
NO hardcoded WikiText, NO hardcoded "skip first 4 positions".

For our target — an abliterated instruct Qwen thinking model — the load-bearing design is an
OVER-WEIGHTED safety stratum + a matched-benign contrast + a WikiText control, so "what
abliteration did to the refusal direction" can be read as a DIFFERENCE of two lenses (fit a
harmful lens and a benign lens that differ only in harmfulness; the diff localizes the moved
direction). On-policy generation is essential: fit at the model's OWN assistant/<think> token
positions, not a teacher model's shipped traces.

Dataset ids/licenses below were verified on the HF Hub. `build_corpus` (the HF-loading +
on-policy sampling pipeline) is the next implementation step; the recipes here are the spec.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PositionMask:
    """Which token positions the Jacobian is averaged over. Role/sink-aware, not a fixed skip
    count (the "skip first N" heuristic is for raw-text BOS sinks; wrong under ChatML)."""

    include_assistant: bool = True
    include_think: bool = True
    include_user: bool = False
    drop_bos_sink: bool = True
    drop_role_tokens: bool = True
    predicate: object | None = None  # optional (token_id, position, role) -> bool


@dataclass
class Stratum:
    """One weighted source in a recipe. `weight`s within a recipe sum to ~1.0."""

    hf_id: str
    weight: float
    kind: str                       # chat | reasoning | safety | benign | creative | multilingual | control
    config: str | None = None       # HF dataset config/subset (e.g. JBB "harmful"/"benign")
    split: str = "train"
    prompt_field: str = ""          # which field holds the user prompt (loader-specific)
    license: str = ""
    gated: bool = False
    note: str = ""


@dataclass
class Recipe:
    """A named, reproducible fitting-corpus spec, stamped onto the lens sidecar as provenance
    (recipe + model SHA + position policy). Counts are PROMPTS, not tokens (~100-500 suffices)."""

    name: str
    strata: list[Stratum] = field(default_factory=list)
    n_prompts: int = 300
    seed: int = 0
    chat_templated: bool = True       # render through the model's own chat template
    on_policy_fraction: float = 0.6   # 0 = human text only; 0.5-0.7 for a chat/reasoning lens
    positions: PositionMask = field(default_factory=PositionMask)


@dataclass
class CorpusItem:
    """One materialized prompt: chat-templated token ids + the position indices the
    Jacobian is averaged over (role/sink-masked), plus where it came from."""

    ids: list[int]
    positions: list[int]
    stratum: str                     # the kind (chat/reasoning/safety/...)
    on_policy: bool                  # True if the assistant span was generated by the model


@dataclass
class Corpus:
    """Materialized fitting corpus: per-prompt items + provenance for the lens sidecar."""

    recipe: Recipe
    items: list = field(default_factory=list)         # list[CorpusItem]
    provenance: dict = field(default_factory=dict)    # recipe name, per-stratum counts, on-policy frac

    def prompts_ids(self) -> list[list[int]]:
        return [it.ids for it in self.items]

    def positions(self) -> list[list[int]]:
        return [it.positions for it in self.items]

    def to_json(self, path) -> None:
        """Serialize the materialized corpus (tokenized items + provenance) so a resumed fit
        reuses the EXACT same items -- crucially skipping on-policy generation (GPU) on resume,
        and guaranteeing the checkpoint's item order matches. Recipe params aren't needed to
        re-fit, so only the recipe name is kept."""
        import json
        from pathlib import Path
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "recipe_name": self.recipe.name,
            "provenance": self.provenance,
            "items": [{"ids": it.ids, "positions": it.positions, "stratum": it.stratum,
                       "on_policy": it.on_policy} for it in self.items],
        }
        Path(path).write_text(json.dumps(payload))

    @classmethod
    def from_json(cls, path) -> "Corpus":
        import json
        from pathlib import Path
        p = json.loads(Path(path).read_text())
        items = [CorpusItem(it["ids"], it["positions"], it["stratum"], it["on_policy"])
                 for it in p["items"]]
        return cls(recipe=Recipe(name=p.get("recipe_name", "loaded")),
                   items=items, provenance=p.get("provenance", {}))


# --- Concrete recipes (from the HF-verified dataset study) ------------------------------------

#: Primary recipe for the abliterated Qwen. Over-weighted safety (25% vs its ~1-3% natural
#: frequency) so the refusal circuitry is ACTIVE at estimation time — the single most important
#: departure from a WikiText lens.
ABLITERATED_QWEN = Recipe(
    name="abliterated-qwen-chat-safety-v1",
    n_prompts=300,
    on_policy_fraction=0.6,
    strata=[
        # 30% general chat / real user turns — on-distribution backbone
        Stratum("allenai/WildChat-1M", 0.30, "chat", license="ODC-BY",
                note="real in-the-wild convs; keep raw user prompts internal (ODC-BY)"),
        # 25% math+code reasoning with CoT — drives the <think> positions (use PROMPTS, regen on-policy)
        Stratum("open-r1/OpenR1-Math-220k", 0.10, "reasoning", license="Apache-2.0",
                note="math; shipped traces are R1's -> use prompts, regenerate on-policy"),
        Stratum("open-thoughts/OpenThoughts-114k", 0.08, "reasoning", license="Apache-2.0"),
        Stratum("nvidia/OpenCodeReasoning", 0.07, "reasoning", config="python", license="CC-BY-4.0"),
        # 25% safety-salient (OVER-WEIGHTED) — the differentiating stratum
        Stratum("JailbreakBench/JBB-Behaviors", 0.13, "safety", config="harmful",
                license="MIT", note="MIT/ungated; has a matched benign config -> difference-of-Jacobians"),
        Stratum("mlabonne/harmful_behaviors", 0.12, "safety", license="AdvBench-derived (MIT)",
                note="matches mlabonne's abliteration recipe; pair with mlabonne/harmless_alpaca"),
        # 12% creative / roleplay — uncensored deployment regime
        Stratum("Gryphe/Sonnet3.5-SlimOrcaDedupCleaned", 0.12, "creative", license="MIT",
                note="uncensored responses (no refusals) -> matches the abliterated regime"),
        # 8% multilingual breadth
        Stratum("CohereLabs/aya_dataset", 0.08, "multilingual", license="Apache-2.0"),
    ],
)

#: Matched harmful/benign pair — fit two lenses that differ ONLY in harmfulness; their diff
#: localizes the direction abliteration moved. Same prompts otherwise.
SAFETY_HARMFUL = Recipe(
    name="safety-harmful-v1", n_prompts=200, on_policy_fraction=0.6,
    strata=[
        Stratum("JailbreakBench/JBB-Behaviors", 0.5, "safety", config="harmful", license="MIT"),
        Stratum("mlabonne/harmful_behaviors", 0.5, "safety", license="AdvBench-derived (MIT)"),
    ],
)
SAFETY_BENIGN = Recipe(
    name="safety-benign-v1", n_prompts=200, on_policy_fraction=0.6,
    strata=[
        Stratum("JailbreakBench/JBB-Behaviors", 0.5, "benign", config="benign", license="MIT"),
        Stratum("mlabonne/harmless_alpaca", 0.5, "benign", license="AdvBench-derived (MIT)"),
    ],
)

#: The control arm — the reference literature's corpus (Neuronpedia's "Salesforce-wikitext",
#: Anthropic/solarkyle's WikiText/C4). Fit it BOTH raw (chat_templated=False, matches the
#: literature) and chat-templated (to isolate template-effect from content-effect). The headline
#: result: the stratified lens diverges from the WikiText lens specifically where abliteration acted.
WIKITEXT_CONTROL = Recipe(
    name="wikitext-control-v1", n_prompts=300, on_policy_fraction=0.0, chat_templated=False,
    strata=[Stratum("Salesforce/wikitext", 1.0, "control", config="wikitext-103-raw-v1",
                    license="CC-BY-SA-3.0", note="raw prose baseline; also allenai/c4 (ODC-BY)")],
)


# --- Implementation --------------------------------------------------------------------------

#: Fields we try, in order, to pull a user prompt out of an arbitrary HF row. `list`-valued
#: fields (conversation/messages) are unwound to their first user turn.
_PROMPT_FIELDS = ("prompt", "text", "question", "problem", "goal", "behavior", "instruction",
                  "query", "Goal", "conversation", "messages", "chosen")


def _extract_prompt(row: dict, field_hint: str = "") -> str | None:
    """Best-effort pull of a single user-prompt string from a dataset row."""
    keys = ([field_hint] if field_hint else []) + list(_PROMPT_FIELDS)
    for k in keys:
        if k not in row:
            continue
        v = row[k]
        if isinstance(v, str) and v.strip():
            return v.strip()
        if isinstance(v, list) and v:                       # conversation/messages
            for turn in v:
                if isinstance(turn, dict):
                    role = turn.get("role") or turn.get("from")
                    content = turn.get("content") or turn.get("value")
                    if role in ("user", "human", "prompter") and isinstance(content, str) and content.strip():
                        return content.strip()
            first = v[0]
            if isinstance(first, dict):
                c = first.get("content") or first.get("value")
                if isinstance(c, str) and c.strip():
                    return c.strip()
            if isinstance(first, str) and first.strip():
                return first.strip()
    return None


def _load_stratum_prompts(stratum: Stratum, n: int, seed: int) -> list[str]:
    """Stream `n` user-prompt strings from `stratum`'s HF dataset (no full download).

    Uses `datasets` in streaming mode + a shuffled buffer so a few hundred prompts don't pull
    gigabytes. Lazy import so the module (and its recipes) load without `datasets` installed.
    """
    from datasets import load_dataset  # lazy: only build_corpus needs it

    ds = load_dataset(stratum.hf_id, stratum.config, split=stratum.split, streaming=True)
    try:
        ds = ds.shuffle(seed=seed, buffer_size=max(1000, n * 5))
    except Exception:
        pass  # some streaming datasets don't support shuffle; take head order
    out: list[str] = []
    for row in ds:
        p = _extract_prompt(row, stratum.prompt_field)
        if p:
            out.append(p)
            if len(out) >= n:
                break
    return out


def _weighted_counts(recipe: Recipe) -> list[int]:
    """Per-stratum prompt counts: `weight * n_prompts`, rounded, adjusted to sum exactly."""
    raw = [s.weight * recipe.n_prompts for s in recipe.strata]
    counts = [int(round(x)) for x in raw]
    diff = recipe.n_prompts - sum(counts)
    # Distribute the rounding remainder onto the largest strata (deterministic).
    order = sorted(range(len(counts)), key=lambda i: -raw[i])
    i = 0
    while diff != 0 and order:
        j = order[i % len(order)]
        counts[j] += 1 if diff > 0 else -1
        if counts[j] < 0:
            counts[j] = 0
        diff = recipe.n_prompts - sum(counts)
        i += 1
    return counts


def _chat_ids(tokenizer, user_text: str, *, add_generation_prompt: bool) -> list[int]:
    return list(tokenizer.apply_chat_template(
        [{"role": "user", "content": user_text}],
        add_generation_prompt=add_generation_prompt, tokenize=True))


def build_positions(ids: list[int], prompt_prefix_len: int, mask: PositionMask,
                    *, think_span: tuple[int, int] | None = None,
                    skip_first: int = 4) -> list[int]:
    """Positions the Jacobian is averaged over, per `mask`. `prompt_prefix_len` is the length
    of the chat-templated prompt through the generation-prompt (so ids[prompt_prefix_len:] is the
    assistant completion, when present).

    - Completion present (on-policy): the assistant span [prompt_prefix_len, len-1). If
      `think_span` is given and `mask.include_think` but not `mask.include_assistant`, restrict
      to the think span. Drops the final position (no next-token target).
    - No completion (human-text): a content span inside the prompt, dropping the BOS/role
      scaffold via `skip_first` and the final generation-prompt position.
    """
    n = len(ids)
    if n < 2:
        return []
    has_completion = n > prompt_prefix_len + 1
    if has_completion:
        lo, hi = prompt_prefix_len, n - 1
        if think_span and mask.include_think and not mask.include_assistant:
            lo, hi = max(lo, think_span[0]), min(hi, think_span[1])
        elif think_span and not mask.include_think and mask.include_assistant:
            # assistant-minus-think: keep [prefix, think_start) + [think_end, len-1)
            keep = [p for p in range(prompt_prefix_len, n - 1)
                    if not (think_span[0] <= p < think_span[1])]
            return keep or [n - 2]
        pos = list(range(lo, hi))
    else:
        start = skip_first if mask.drop_bos_sink or mask.drop_role_tokens else 0
        start = min(start, max(0, prompt_prefix_len - 2))
        pos = list(range(start, prompt_prefix_len - 1))
    if mask.predicate is not None:
        pos = [p for p in pos if mask.predicate(ids[p], p, "assistant" if has_completion else "user")]
    return pos or [n - 2]


def generate_on_policy(model, tokenizer, user_texts: list[str], *, max_tokens: int = 64,
                       temp: float = 0.7, seed: int = 0) -> list[list[int]]:
    """GPU step (separated so the offline corpus build needs no model/server): for each user
    text, chat-template with a generation prompt and append the model's OWN sampled completion.
    Returns the full token-id sequence per prompt (prompt-prefix + generated assistant span).

    Uses mlx_lm.generate.stream_generate for a real on-policy sample (incl. <think> if the
    model emits it). Call only with the server stopped (holds the GPU)."""
    import mlx.core as mx
    from mlx_lm.generate import stream_generate
    from mlx_lm.sample_utils import make_sampler

    mx.random.seed(seed)
    sampler = make_sampler(temp=temp)
    out = []
    for text in user_texts:
        prompt_ids = _chat_ids(tokenizer, text, add_generation_prompt=True)
        gen_ids = []
        for resp in stream_generate(model, tokenizer, prompt=prompt_ids,
                                    max_tokens=max_tokens, sampler=sampler):
            gen_ids.append(resp.token)
        out.append(list(prompt_ids) + gen_ids)
    return out


def build_corpus(model, tokenizer, recipe: Recipe, *, on_policy_max_tokens: int = 64) -> Corpus:
    """Render `recipe` into a Corpus of chat-templated, position-masked prompts.

    Offline (no model needed): stream + weight-sample each stratum, chat-template, tokenize, and
    build human-text position masks. On-policy (needs `model`, GPU): for `on_policy_fraction` of
    prompts, append the model's own sampled completion and mask the generated assistant span.
    Pass `model=None` to build the human-text-only corpus (all masks over prompt content) --
    useful to prepare the corpus with the server up, then generate on-policy once it's stopped.

    `tokenizer` MUST be the mlx-lm `TokenizerWrapper` (from `mlx_lm.load` / `mlx_lm.tokenizer_utils.
    load`), which carries the model's jinja chat template. A raw `transformers.AutoTokenizer` loaded
    from a local mlx model dir may lack the template (some dirs ship it as a separate `*.jinja`
    file) and would silently produce near-empty chat-templated sequences.

    Gated datasets (LMSYS/AdvBench/wildjailbreak) need an HF token; the recipes prefer ungated
    MIT/ODC-BY substitutes. Keep raw user prompts internal (ODC-BY attribution).
    """
    # Guard: a real chat template must expand a probe to a non-trivial ChatML sequence. Catches
    # a template-less tokenizer before a whole corpus is built with empty prompts.
    if recipe.chat_templated:
        probe = _chat_ids(tokenizer, "probe", add_generation_prompt=True)
        if len(probe) < 5:
            raise ValueError(
                "tokenizer produced a near-empty chat-templated sequence for a probe prompt "
                f"(len={len(probe)}); pass the mlx-lm TokenizerWrapper (it carries the jinja "
                "chat template), not a raw AutoTokenizer from the model dir")
    counts = _weighted_counts(recipe)
    per_stratum: list[tuple[Stratum, list[str]]] = []
    prov_counts = {}
    for stratum, k in zip(recipe.strata, counts):
        if k <= 0:
            continue
        prompts = _load_stratum_prompts(stratum, k, recipe.seed)
        per_stratum.append((stratum, prompts))
        # Composite key: strata can share an hf_id (e.g. JBB harmful vs benign configs/splits),
        # so keying on hf_id alone would collide and undercount.
        key = ":".join(p for p in (stratum.hf_id, stratum.config, stratum.split) if p)
        prov_counts[key] = prov_counts.get(key, 0) + len(prompts)

    # Flatten with a deterministic on-policy split: the first `on_policy_fraction` of EACH
    # stratum (post-shuffle) is generated on-policy; the rest stay human-text.
    items: list[CorpusItem] = []
    for stratum, prompts in per_stratum:
        n_op = int(round(len(prompts) * recipe.on_policy_fraction)) if model is not None else 0
        op_texts, human_texts = prompts[:n_op], prompts[n_op:]

        if op_texts:
            full_seqs = generate_on_policy(model, tokenizer, op_texts,
                                           max_tokens=on_policy_max_tokens, seed=recipe.seed)
            for text, ids in zip(op_texts, full_seqs):
                prefix = len(_chat_ids(tokenizer, text, add_generation_prompt=True))
                pos = build_positions(ids, prefix, recipe.positions)
                items.append(CorpusItem(ids, pos, stratum.kind, on_policy=True))

        for text in human_texts:
            ids = _chat_ids(tokenizer, text, add_generation_prompt=recipe.chat_templated)
            prefix = len(ids)  # no completion -> the whole thing is the prompt prefix
            pos = build_positions(ids, prefix, recipe.positions)
            items.append(CorpusItem(ids, pos, stratum.kind, on_policy=False))

    provenance = {
        "recipe": recipe.name,
        "n_prompts": len(items),
        "on_policy_fraction": recipe.on_policy_fraction if model is not None else 0.0,
        "chat_templated": recipe.chat_templated,
        "strata": prov_counts,
        "seed": recipe.seed,
    }
    return Corpus(recipe=recipe, items=items, provenance=provenance)
